fcrepo-auth-roles-basic/src/main/java/org/fcrepo/auth/roles/basic/BasicRolesAuthorizationDelegate.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/BasicRolesAuthorizationDelegateRemoveChildrenRecursiveTest.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/BasicRolesAuthorizationDelegateTest.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/AbstractBasicRolesIT.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/BasicRolesAdminIT.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/BasicRolesReaderIT.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/BasicRolesUnauthenticatedUserIT.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/BasicRolesWriterIT.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AbstractRolesAuthorizationDelegate.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRoles.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesProvider.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesResources.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesTypes.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/Constants.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AbstractRolesAuthorizationDelegateTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesProviderTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesResourcesTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesTypesTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/AbstractCommonRolesIT.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/AbstractRolesIT.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/AccessRolesIT.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/RolesFadTestObjectBean.java
See: https://jira.duraspace.org/browse/FCREPO-1297
Changed copyright year from 2014 to 2015
=> updated copyright year to 2015

fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/AbstractRolesIT.java
Related to: https://jira.duraspace.org/browse/FCREPO-1537
=> Minor impact of disallowing empty path segments

fcrepo-auth-roles-basic/pom.xml, fcrepo-auth-roles-common/pom.xml, pom.xml
See: https://jira.duraspace.org/browse/FCREPO-1591
=> Package as OSGi bundle

fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AbstractRolesAuthorizationDelegate.java
https://jira.duraspace.org/browse/FCREPO-1714
=> FCREPO-1714. Moved FedoraUserSecurityContext instantiation to fad.

fcrepo-auth-roles-basic/src/test/resources/spring-test/rest.xml, fcrepo-auth-roles-common/src/test/resources/spring-test/rest.xml
Related to: https://jira.duraspace.org/browse/FCREPO-1696
=> Remove minter bean from integration test configuration

fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesResources.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesResourcesTest.java
See: https://jira.duraspace.org/browse/FCREPO-1824
=> rename FedoraJcrTypes class to FedoraTypes, based on upstream changes

fcrepo-auth-roles-basic/src/main/java/org/fcrepo/auth/roles/basic/BasicRolesAuthorizationDelegate.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/BasicRolesAuthorizationDelegateRemoveChildrenRecursiveTest.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/BasicRolesAuthorizationDelegateTest.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/AbstractBasicRolesIT.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/BasicRolesAdminIT.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/BasicRolesReaderIT.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/BasicRolesUnauthenticatedUserIT.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/BasicRolesWriterIT.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AbstractRolesAuthorizationDelegate.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRoles.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesProvider.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesResources.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesTypes.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/Constants.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/RbAclAccessRolesProvider.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AbstractRolesAuthorizationDelegateTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesProviderTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesResourcesTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesTypesTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/AbstractCommonRolesIT.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/AbstractRolesIT.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/AccessRolesIT.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/RolesFadTestObjectBean.java
Resolves: https://jira.duraspace.org/browse/FCREPO-1583
=>  Reformat license headers

fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/BasicRolesAuthorizationDelegateRemoveChildrenRecursiveTest.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/BasicRolesAuthorizationDelegateTest.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AbstractRolesAuthorizationDelegate.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRoles.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesProvider.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/RbAclAccessRolesProvider.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AbstractRolesAuthorizationDelegateTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesProviderTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesTest.java
Addresses: https://jira.duraspace.org/browse/FCREPO-1955
=> change AccessRolesProvider::getRoles to return a Collection instead of a List

fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRoles.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesResources.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesResourcesTest.java
Addresses: https://jira.duraspace.org/browse/FCREPO-1869
Depends on https://github.com/fcrepo4/fcrepo4/pull/1032
=> fallout from removing FedoraResource::getNode

fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/BasicRolesAuthorizationDelegateRemoveChildrenRecursiveTest.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AbstractRolesAuthorizationDelegate.java
https://jira.duraspace.org/browse/FCREPO-2027
=> Fixed a bug that resulted in an exception when deleting properties.

fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AbstractRolesAuthorizationDelegate.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesTypes.java
Addresses: https://jira.duraspace.org/browse/FCREPO-2047
=> Replace @Autowired annotation with @Inject

LICENSE, NOTICE, fcrepo-auth-roles-basic/src/main/java/org/fcrepo/auth/roles/basic/BasicRolesAuthorizationDelegate.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/BasicRolesAuthorizationDelegateRemoveChildrenRecursiveTest.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/BasicRolesAuthorizationDelegateTest.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/AbstractBasicRolesIT.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/BasicRolesAdminIT.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/BasicRolesReaderIT.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/BasicRolesUnauthenticatedUserIT.java, fcrepo-auth-roles-basic/src/test/java/org/fcrepo/auth/roles/basic/integration/BasicRolesWriterIT.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AbstractRolesAuthorizationDelegate.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRoles.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesProvider.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesResources.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesTypes.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/Constants.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/RbAclAccessRolesProvider.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AbstractRolesAuthorizationDelegateTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesProviderTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesResourcesTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesTypesTest.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/AbstractCommonRolesIT.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/AbstractRolesIT.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/AccessRolesIT.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/integration/RolesFadTestObjectBean.java
Related to: https://jira.duraspace.org/browse/FCREPO-2066
=> Update source headers to not require annual update

fcrepo-auth-roles-basic/pom.xml, fcrepo-auth-roles-common/pom.xml, pom.xml
Addresses: https://jira.duraspace.org/browse/FCREPO-2091
=> Increment version numbers to 4.7.0-SNAPSHOT

fcrepo-auth-roles-basic/pom.xml, fcrepo-auth-roles-basic/src/test/resources/repository.json, fcrepo-auth-roles-common/pom.xml, fcrepo-auth-roles-common/src/test/resources/spring-test/repo.xml, pom.xml
Related to: https://jira.duraspace.org/browse/FCREPO-1994
=> Update configuration to work with MODE5

fcrepo-auth-roles-common/pom.xml, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRoles.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRolesResources.java, fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/Constants.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesResourcesTest.java
Addresses: https://jira.duraspace.org/browse/FCREPO-1672
=> Migrate to Jena 3.x

pom.xml
=> Update version numbers in Maven config

fcrepo-auth-roles-common/src/main/java/org/fcrepo/auth/roles/common/AccessRoles.java, fcrepo-auth-roles-common/src/test/java/org/fcrepo/auth/roles/common/AccessRolesTest.java
Addresses: https://jira.duraspace.org/browse/FCREPO-2278
Depends on https://github.com/fcrepo4/fcrepo4/pull/1128
=> Follow-on for adding a batch-aware session class

fcrepo-auth-roles-basic/pom.xml, pom.xml
Related to: https://jira.duraspace.org/browse/FCREPO-2285
=> Update junit version number

pom.xml
See: https://github.com/fcrepo4-exts/fcrepo-module-auth-rbacl/pull/46
@awoods
=> Fix repo url; Resolves GitHub pages build issues.

fcrepo-auth-roles-basic/pom.xml, fcrepo-auth-roles-common/pom.xml, pom.xml
Move 4.7.3-maintenance commits to the 4.7-maintenance branch
* Then remove the 4.7.3-maintenance branch
@ruebot
=> 4.7.3 maintenance

fcrepo-auth-roles-basic/pom.xml, fcrepo-auth-roles-common/pom.xml, pom.xml
Finalize release by merging 4.7.5-maintenance into 4.7-maintenance.
=> Finalize release by merging 4.7.5-maintenance into 4.7-maintenance
